import SwiftUI
import UIKit

/// Full verdict report for one analysis.
struct ResultDetailView: View {
    let record: ScanRecord
    @Environment(LanguageStore.self) private var lang

    var body: some View {
        ZStack {
            GuardBackdrop()

            ScrollView {
                VStack(spacing: 16) {
                    verdictHeader

                    if let data = record.thumbnailData, let image = UIImage(data: data) {
                        Color(.secondarySystemBackground)
                            .frame(height: 200)
                            .overlay {
                                Image(uiImage: image)
                                    .resizable()
                                    .aspectRatio(contentMode: .fill)
                                    .allowsHitTesting(false)
                            }
                            .clipShape(.rect(cornerRadius: 20))
                            .overlay {
                                RoundedRectangle(cornerRadius: 20)
                                    .strokeBorder(GuardTheme.cardStroke, lineWidth: 1)
                            }
                    }

                    if let url = record.inspectedURL {
                        SectionCard(title: lang.tr("Lien analysé", "Analyzed link"), symbol: "link") {
                            Text(url)
                                .font(.system(size: 13, design: .monospaced))
                                .foregroundStyle(GuardTheme.accentLight)
                                .textSelection(.enabled)
                        }
                    }

                    SectionCard(title: lang.tr("Explication", "Explanation"), symbol: "text.book.closed.fill") {
                        Text(record.explanationText(french: lang.isFrench))
                            .font(.system(size: 14.5))
                            .lineSpacing(3)
                            .foregroundStyle(GuardTheme.textPrimary.opacity(0.92))
                    }

                    let suspicious = record.suspicious(french: lang.isFrench)
                    if !suspicious.isEmpty {
                        SectionCard(
                            title: lang.tr("Éléments suspects", "Suspicious signals"),
                            symbol: "exclamationmark.triangle.fill",
                            tint: GuardTheme.danger
                        ) {
                            VStack(alignment: .leading, spacing: 10) {
                                ForEach(suspicious, id: \.self) { item in
                                    SignalRow(text: item, symbol: "xmark.circle.fill", tint: GuardTheme.danger)
                                }
                            }
                        }
                    }

                    let reassuring = record.reassuring(french: lang.isFrench)
                    if !reassuring.isEmpty {
                        SectionCard(
                            title: lang.tr("Éléments rassurants", "Reassuring signals"),
                            symbol: "checkmark.seal.fill"
                        ) {
                            VStack(alignment: .leading, spacing: 10) {
                                ForEach(reassuring, id: \.self) { item in
                                    SignalRow(text: item, symbol: "checkmark.circle.fill", tint: GuardTheme.accent)
                                }
                            }
                        }
                    }

                    let advice = record.adviceList(french: lang.isFrench)
                    if !advice.isEmpty {
                        SectionCard(
                            title: lang.tr("Que faire maintenant", "What to do now"),
                            symbol: "lightbulb.fill",
                            tint: GuardTheme.warning
                        ) {
                            VStack(alignment: .leading, spacing: 10) {
                                ForEach(advice, id: \.self) { item in
                                    SignalRow(text: item, symbol: "arrow.right.circle.fill", tint: GuardTheme.warning)
                                }
                            }
                        }
                    }

                    Text(lang.tr(
                        "Analyse générée par intelligence artificielle. Elle vous aide à décider, mais ne remplace pas la vérification directe auprès de l'organisation concernée.",
                        "This analysis is generated by artificial intelligence. It helps you decide, but does not replace checking directly with the organisation involved."
                    ))
                    .font(.system(size: 11.5))
                    .foregroundStyle(GuardTheme.textMuted)
                    .multilineTextAlignment(.center)
                    .padding(.horizontal, 8)
                    .padding(.top, 4)
                }
                .padding(.horizontal)
                .padding(.bottom, 32)
            }
        }
        .navigationTitle(lang.tr("Rapport", "Report"))
        .navigationBarTitleDisplayMode(.inline)
        .toolbarBackground(.hidden, for: .navigationBar)
    }

    private var verdictHeader: some View {
        VStack(spacing: 14) {
            RiskGaugeView(
                score: record.riskScore,
                level: record.riskLevel,
                caption: record.riskLevel.shortLabel(french: lang.isFrench)
            )
            .padding(.top, 8)

            Text(record.riskLevel.title(french: lang.isFrench))
                .font(.system(size: 24, weight: .bold, design: .rounded))
                .foregroundStyle(GuardTheme.textPrimary)

            HStack(spacing: 6) {
                Image(systemName: record.source.symbol)
                    .font(.system(size: 11, weight: .semibold))
                Text(record.detectedSourceText(french: lang.isFrench))
                    .font(.system(size: 12, weight: .semibold))
            }
            .foregroundStyle(GuardTheme.accentLight)
            .padding(.horizontal, 12)
            .padding(.vertical, 7)
            .background(GuardTheme.accent.opacity(0.12), in: .capsule)
            .overlay { Capsule().strokeBorder(GuardTheme.accentStroke, lineWidth: 1) }

            Text(record.summaryText(french: lang.isFrench))
                .font(.system(size: 15.5))
                .lineSpacing(3)
                .multilineTextAlignment(.center)
                .foregroundStyle(GuardTheme.textPrimary.opacity(0.9))
                .padding(.horizontal, 4)
        }
    }
}
